# Generated by Django 3.2 on 2021-05-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onepixel',
            name='PixelColor',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет'),
        ),
    ]
